class ImportShopListV1 < ActiveRecord::Migration
  def self.up
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京中关村津乐汇店",	:province => "北京",	:city => "",	:address => "北京市海淀区中关村大街15号中关村购物中心D区津乐汇地下二层",				:name_en => "Beijing Zhongguancun La Vita",				:province_en => "Beijing",		:city_en => "",		:address_en => "B2 La Vita, D Area Zhonguancun Shopping Center, No.15 Zhongguancun Street, Haidian District, Beijing",				:latitude => "39.97987",		:longtitude => "116.316429")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京通县阳光生活广场",	:province => "北京",	:city => "",	:address => "北京市通州区九棵树瑞都景园北区A1号楼新阳光生活广场一层G35",				:name_en => "Life Square",								:province_en => "Beijing",		:city_en => "",		:address_en => "G35, 1F Life Square, Building A1, North Area of Ruidu Garden, Jiukeshu Street, Tongzhou District, Beijing",		:latitude => "39.889867",			:longtitude => "116.656201")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京富力城广场",		:province => "北京",	:city => "",	:address => "北京市朝阳区东三环中路富力广场南区二层207号商铺",					:name_en => "Viva Plaza",								:province_en => "Beijing",		:city_en => "",		:address_en => "No.207. 2F South Area of Viva Plaza, East 3rd-Ring Road, Chaoyang District, Beijing",								:latitude => "39.896008",		:longtitude => "116.460743")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京怀柔京北大世界",	:province => "北京",	:city => "",	:address => "北京市怀柔区府前街14号怀柔京北大世界二层",						:name_en => "Huairou Jingbei",							:province_en => "Beijing",		:city_en => "",		:address_en => "2F Huairou Jingbei Shopping Mall, No.14 Fuqian Street, Huairou District, Beijing",									:latitude => "40.33732",		:longtitude => "116.633949")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京朝阳大悦城",		:province => "北京",	:city => "",	:address => "北京市朝阳区朝阳北路大悦城4F-25 theCarnaby专柜",				:name_en => "Beijing Chaoyang Joycity",					:province_en => "Beijing",		:city_en => "",		:address_en => "4F Chaoyang Joy city, No.101 North Chaoyang Road, Chaoyang District, Beijing",										:latitude => "39.924811",	:longtitude => "116.518335")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京8号购物广场",	:province => "北京",	:city => "",	:address => "北京市海淀区学清路甲8号圣熙8号购物中心三层",						:name_en => "No. 8 Plaza",								:province_en => "Beijing",		:city_en => "",		:address_en => "3F No.8 Plaza， No.A-8 Xueqing Road, Haidian District, Beijing",													:latitude => "40.016178",	:longtitude => "116.353648")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "北京东方银座",		:province => "北京",	:city => "",	:address => "北京市东城区东直门外大街48号银座商场L1层14&15号铺位",				:name_en => "Oriental Kenzo Plaza",						:province_en => "Beijing",		:city_en => "",		:address_en => "Shop 14-15, Level 1 , Oriental Kenzo Plaza , 48 Dongzhimenwai Street, Dongcheng District, Beijing, China.",		:latitude => "39.943436",	:longtitude => "116.435509")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "福州大洋一店",		:province => "福建",	:city => "",	:address => "福州市鼓楼区八一七北路133号大洋百货三楼",						:name_en => "Grand Ocean I",							:province_en => "Fujian",		:city_en => "",		:address_en => "3F Grand Ocean, No.133 North Bayiqi Road,Gulou District, Fuzhou",													:latitude => "26.084365",	:longtitude => "119.300022")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "福州大洋三店",		:province => "福建",	:city => "",	:address => "福建省福州市鼓楼区五一中路18号大洋三店二楼嘉耐芘专柜",					:name_en => "Grand Ocean III",							:province_en => "Fujian",		:city_en => "",		:address_en => "2F Grand Ocean, No.18 Middle of Wuyi Road,Gulou District, Fuzhou",													:latitude => "26.076482",	:longtitude => "119.31073")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "杭州大厦",		:province => "浙江",	:city => "",	:address => "杭州市下城区武林路一号杭州大厦A座5楼the Carnaby专柜",				:name_en => "Hangzhou Tower",							:province_en => "Zhejiang",		:city_en => "",		:address_en => "5F Building A Hangzhou Tower, No.1 Wulin Road,xiacheng District Hangzhou",											:latitude => "30.27306",		:longtitude => "120.161526")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "苏州久光",		:province => "江苏",	:city => "",	:address => "苏州市工业园区旺墩路268号苏州久光百货三楼the Carnaby专柜 ",			:name_en => "Suzhou Jiu-Guang",							:province_en => "Jiangsu",		:city_en => "",		:address_en => "3F, Suzhou Jiu-Guang Department Store, Suzhou Industrial Park,268 Wang Dun Road, Suzhou ",							:latitude => "31.32578",		:longtitude => "120.71537")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海日月光JUMBO",	:province => "上海",	:city => "",	:address => "上海市徐汇区徐家汇路618号日月光商场1楼thecarnaby专柜",			:name_en => "SM Center",								:province_en => "Shanghai",		:city_en => "",		:address_en => "1F,SM Center,No.618 Xujiahui Road,Xuhui District, Shanghai",														:latitude => "31.210159",	:longtitude => "121.468449")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海九六",		:province => "上海",	:city => "",	:address => "上海市浦东新区东方路796号九六广场129室",						:name_en => "96 Plaza",									:province_en => "Shanghai",		:city_en => "",		:address_en => "Room 129, 96 Plaza, No.796 Dongfang Road, Pudong New District, Shanghai",											:latitude => "31.228032",	:longtitude => "121.525097")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海港汇",		:province => "上海",	:city => "",	:address => "上海市徐汇区虹桥路1号3楼338Bthecarnaby专柜",				:name_en => "Shanghai Grand Gateway Plaza",				:province_en => "Shanghai",		:city_en => "",		:address_en => "338B, 3F Grand Gateway Plaza, No.1 Hongqiao Road, Xuhui District, Shanghai",										:latitude => "31.197385",	:longtitude => "121.437378")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海大宁国际",		:province => "上海",	:city => "",	:address => "上海市闸北区共和新路1988号204 205 206单元",					:name_en => "Daning International Commercial",			:province_en => "Shanghai",		:city_en => "",		:address_en => "204-206,Block 10,No 1988, GongHeXin Road,zhabei District,shanghai",												:latitude => "31.281485",	:longtitude => "121.454201")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海南站银泰中岛店",	:province => "上海",	:city => "",	:address => "上海市徐汇区老沪闵路289号上海南站地下商场北馆第一层B区 15号 36号专区",		:name_en => "Shanghai Yintai (South Railway Station)",	:province_en => "Shanghai",		:city_en => "",		:address_en => "Shop B-15 & Shop B-36，9001_3, Lao Hu Min Road,Xuhui District, shanghai",											:latitude => "31.155784",	:longtitude => "121.427293")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海南站银泰边厅店",	:province => "上海",	:city => "",	:address => "上海市徐汇区老沪闵路289号上海南站地下商场北馆第一层B区 15号 36号专区",		:name_en => "Shanghai Yintai (South Railway Station)",	:province_en => "Shanghai",		:city_en => "",		:address_en => "Shop B-15 & Shop B-36，9001_3, Lao Hu Min Road,Xuhui District, shanghai",											:latitude => "31.155784",	:longtitude => "121.427293")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "上海百联西郊",		:province => "上海",	:city => "",	:address => "上海市长宁区仙霞西路剑河路百联西郊购物中心二层2216室",					:name_en => "Bailian Xijiao Shopping Mall",				:province_en => "Shanghai",		:city_en => "",		:address_en => "Shop 2216, 88 West Xian Xia Road,Changning District, Shanghai",													:latitude => "31.211921",	:longtitude => "121.369743")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "重庆煌华新纪元店",	:province => "重庆",	:city => "",	:address => "重庆市沙坪坝区渝碚路双巷子六号煌华新纪元购物广场一楼十二the carnaby专柜",	:name_en => "Huanghua New Era",							:province_en => "Chongqing",	:city_en => "",		:address_en => "1F Huanghua New Era, No.6 Shuangxiangzi Walking Street, Sanxia Square, Shapingba District, Chongqing City",		:latitude => "29.565395",	:longtitude => "106.461296")
    Shop.create!(:shop_type_id => Shop::RETAIL,	:name => "重庆西城天街新馆",	:province => "重庆",	:city => "",	:address => "重庆市九龙坡区杨家坪珠江路48号龙湖西城天街新馆1F层03号",				:name_en => "PARADISE WALK SHOPPING MALL PART",			:province_en => "Chongqing",	:city_en => "",		:address_en => "Shop 03, 1F Paradise Walk Shopping Mall, Zhujiang Road, Yangjiapin Jiulongpo District, Chongqing",					:latitude => "29.514019",	:longtitude => "106.517258")
  end

  def self.down
  end
end
